# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-10 19:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0003_auto_20170810_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='data_id',
        ),
    ]
