# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-10 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0004_remove_events_data_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='data_id',
            field=models.IntegerField(default=123),
        ),
    ]
